---
object_type: instance
version: 1.0
object:
  attributes:
    display_name:
    name: default
    inherits:
    description:
  fields:
  - db_hostname:
      value: 10.40.141.5
  - db_password:
      value:
  - meth1:
      value: vmname
