---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: default
    inherits: 
    description: 
  fields:
  - db_password:
      value: redhat
  - meth1:
      value: vmname
